kind: Service
apiVersion: v1
metadata:
  name: quote-react-app
  labels:
    app: quote-react-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: quote-react-app
