apiVersion: v1
kind: Service
metadata:
  name: db-test-service
  labels:
    app: database
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31337
      protocol: TCP
  selector:
    app: database
